on:
  push:
    branches:
      - main

permissions:
  # id-token required for npm OIDC
  # https://docs.npmjs.com/trusted-publishers#step-2-configure-your-cicd-workflow
  id-token: write
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: npm-publish
    steps:
      - name: Checkout the main branch
        uses: actions/checkout@v4
        # Only a single commit is fetched by default
        # we need full repo history with tags, so we are setting fetch-depth: 0
        with:
          fetch-depth: 0
          filter: tree:0

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"
          registry-url: "https://registry.npmjs.org"

      - name: Install npm 11
        run: npm install -g npm@11

      - name: Install packages
        run: npm ci

      - name: Sets the base and head SHAs for the nx affected commands in CI
        uses: nrwl/nx-set-shas@v4

      - name: Build affected libs
        run: npx nx affected -t build

      - name: Run nx release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # https://github.com/nrwl/nx/issues/22066#issuecomment-2576366862
          npm_config_legacy_peer_deps: false
          npm_config_loglevel: verbose
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          npx nx release --yes
